---
version: '2'
services:
  # Can't use service elasticsearch=<num> for now due to named volumes
  elasticsearch:
  # Equivalent to:
  # docker run --rm --cap-add=IPC_LOCK --ulimit memlock=-1:-1 --ulimit nofile=65536:65536 -t -P --memory="4g" -e ES_JAVA_OPTS="-Xms2g -Xmx2g" -v esdata:/usr/share/elasticsearch/data elasticsearch:5.0.0-alpha5 bin/elasticsearch
    build:
      context: elasticsearch-docker/build/elasticsearch
      args:
        ELASTICSEARCH_VERSION: "${ELASTICSEARCH_VERSION}"
    cap_add:
      - IPC_LOCK
    command: bin/elasticsearch -E discovery.zen.minimum_master_nodes=${ES_NODE_COUNT}
    environment:
      ES_JAVA_OPTS: "-Xms2g -Xmx2g"
    image: "elasticsearch:${ELASTICSEARCH_VERSION}"
    mem_limit: 4g
    ports:
      - 9200:9200
      - 9300
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - esdata1:/usr/share/elasticsearch/data

  kibana:
      build: kibana-docker
      hostname: kibana
      environment:
        - HOST=elasticsearch
        - USER=elastic
        - PASS=changeme
      volumes:
          - ./kibana-docker/config/kibana:/opt/config/kibana
      ports:
          - 5601:5601
      links:
          - elasticsearch

  metricbeat:
    build: docker-metricbeat
    hostname: MySQL_Server_1
    links:
      - elasticsearch

  dashboard:
    build: docker-metricbeat
    environment:
      - HOST=elasticsearch
      - USER=elastic
      - PASS=changeme
    links:
      - elasticsearch
    entrypoint: 
      - sh 
      - wait-for-elastic.sh 
 
  watch:
    build: watches-docker
    environment:
      - HOST=elasticsearch
      - USER=elastic
      - PASS=changeme

  load-data:
    build: load-data-docker
    environment:
      - HOST=elasticsearch
      - USER=elastic
      - PASS=changeme
    
volumes:
  esdata1:
    driver: local
